### ISSUE TITLE
KeyError: "['Receiving' 'Rushing' 'Scoring' 'Fumbles'] not found in axis"

### ISSUE THREAD

**Issue by Smiling-Robotics** [vtekur/FantasyFootballPredictor#1]
Hello, love this was hoping to play around with it as I had a similar idea for sports analysis however when running the "final_data_qb, current_year_data_qb = createDataset(reversed(range(2008,2019)), 'QB')" call I get the error KeyError: "['Receiving' 'Rushing' 'Scoring' 'Fumbles'] not found in axis" I am not sure why and was hoping you had some idea. Thanks

**Comment by vtekur** [comment]
Interesting - I don't seem to be getting that error when I run the notebook. Can you describe the specific steps that you took to produce this error?

**Comment by Smiling-Robotics** [comment]
Hey thanks for the quick response! I download and extract the repo to a local directory that I am running jupyter from, at that point I run the notebook and am just stepping through the code until it errors out.

**Comment by vtekur** [comment]
Are you just running each cell once, or multiple times?

**Comment by vtekur** [comment]
Perhaps you have a different version of pandas installed than I do? I have version 0.25.0 installed

**Comment by Smiling-Robotics** [comment]
Woo that was it I was running 0.23.4 after updating Pandas it ran just fine thank you!

**Comment by vtekur** [comment]
Amazing!
